# This is a basic workflow to help you get started with Actions

name: BuildAndTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build and test
        run: |
         cd ./src/cpp/dpgen/
         ./build.sh
         ./test.sh testreport.txt | tee testresult.txt
         status=${PIPESTATUS[0]}
         echo $status
         exit $status
         
      - name: output report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: src/cpp/dpgen/testreport.txt
      - name: output result
        uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: src/cpp/dpgen/testresult.txt

